### ISSUE TITLE
Design improvements for article page

### ISSUE THREAD

**Issue by psiemens** [ubyssey/ubyssey-dispatch-theme#357]
We want to brainstorm some new design elements for the [article page](https://www.ubyssey.ca/news/ono-residential-school-apology-pushed/), generate a list of possible improvements, and then implement the best ideas.

**Tasks:**
- [ ] Conduct preliminary research
    - What strategies are other news websites using?
    - How can we better serve mobile users?
    - How can we encourage users to engage with multimedia (photos, videos)
    - What strategies can we use to bring social media users to additional content
- [ ] Generate a list of specific design improvements
    - Can be as simple notes or sketches -- very low fidelity
- [ ] Present ideas to the rest of the team (volunteers, editors) and narrow down the best ones
- [ ] Create high-fidelity mockups for each
- [ ] Implement them in code!

**Comment by bf777** [comment]
I'd be interested in working on this as well!

**Comment by psiemens** [comment]
@bf777 Sweet. Are you interested in just the coding or do you want to help with design as well?

**Comment by bf777** [comment]
@psiemens I'd be interested in coding and design!

**Comment by JamieRL** [comment]
Closing for the time being. We've implemented a number of redesigns this summer but this may be worth looking into in the future if someone is interested.
