### ISSUE TITLE
📣 Meta-Feature Request 📣

### ISSUE THREAD

**Issue by jumbosushi** [ubyssey/ubyssey-dispatch-theme#607]
Features / Bug fixes that editors want 

## New Feature Request

- [ ] Better Tableau Integration #600
- [ ] Separate Video Section #601
- [ ] Invite involvement from readers #604  
- [ ] Ubyssey PWA add to home screen #606
- [ ] Notification (especially for breaking, big school events) #492 
- [ ] Reddit Share Button #608
- [ ] Article publish scheduling feature (requires flex update)

## Maintenance
- [ ] Search on ubyssey.ca
- [ ] Only by title rn, so allow search by tag, author, keywords
- [ ] Bio for each author
- [ ] Old ubyssey.ca
- [ ] Article disappears from Save
- [ ] Image order by most recent
- [x] Cookies

- [ ] “Contact Us” is only reachable from “About Us” page
- [ ] Articles disappearing from search (ex. culture) (previously fixed?)
- [ ] Filter by section causes the glitch to disable filter (current fix is hard refresh)
- [ ] Ubyssey ad is outdated/wrong (ex. “Hiring Video Producer”)
- [ ] iOS renders the text
